/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FormExampleImport } from './routes/form-example'
import { Route as DialogsExampleImport } from './routes/dialogs-example'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FormExampleRoute = FormExampleImport.update({
  id: '/form-example',
  path: '/form-example',
  getParentRoute: () => rootRoute,
} as any)

const DialogsExampleRoute = DialogsExampleImport.update({
  id: '/dialogs-example',
  path: '/dialogs-example',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dialogs-example': {
      id: '/dialogs-example'
      path: '/dialogs-example'
      fullPath: '/dialogs-example'
      preLoaderRoute: typeof DialogsExampleImport
      parentRoute: typeof rootRoute
    }
    '/form-example': {
      id: '/form-example'
      path: '/form-example'
      fullPath: '/form-example'
      preLoaderRoute: typeof FormExampleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dialogs-example': typeof DialogsExampleRoute
  '/form-example': typeof FormExampleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dialogs-example': typeof DialogsExampleRoute
  '/form-example': typeof FormExampleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dialogs-example': typeof DialogsExampleRoute
  '/form-example': typeof FormExampleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dialogs-example' | '/form-example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dialogs-example' | '/form-example'
  id: '__root__' | '/' | '/dialogs-example' | '/form-example'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DialogsExampleRoute: typeof DialogsExampleRoute
  FormExampleRoute: typeof FormExampleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DialogsExampleRoute: DialogsExampleRoute,
  FormExampleRoute: FormExampleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dialogs-example",
        "/form-example"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dialogs-example": {
      "filePath": "dialogs-example.tsx"
    },
    "/form-example": {
      "filePath": "form-example.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
